jobs:
- job: CreateFolderJob
  pool:
    name: 'default'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Value of myVariable is: $(myVariable)"
        exit 0