[pytest]
pythonpath = src src/py-phone-caller-utils
required_plugins = pytest-asyncio pytest-env pytest-aiohttp
asyncio_mode = auto
env =
	CALLER_CONFIG=src/config/settings.toml
	DYNACONF_COMMONS__ASTERISK_PASS=test_asterisk_pass
	DYNACONF_DATABASE__DB_PASSWORD=test_db_password
	DYNACONF_CALLER_SMS__TWILIO_ACCOUNT_SID=test_twilio_sid
	DYNACONF_CALLER_SMS__TWILIO_AUTH_TOKEN=test_twilio_token
	DYNACONF_PY_PHONE_CALLER_UI__UI_SECRET_KEY=test_ui_secret_key
	DYNACONF_PY_PHONE_CALLER_UI__ADMIN_PASSWORD=test_admin_password
