#!/usr/bin/env python3
"""
Convert TOML configuration files into Dynaconf-compatible environment files.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import sys
# noinspection PyCompatibility
import tomllib
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any


DEFAULT_PREFIX = "DYNACONF"


def load_toml_file(path: Path) -> dict[str, Any]:
    with path.open("rb") as toml_file:
        return tomllib.load(toml_file)


def merge_dicts(base: dict[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    for key, value in override.items():
        existing_value = base.get(key)
        if isinstance(existing_value, dict) and isinstance(value, Mapping):
            merge_dicts(existing_value, value)
        else:
            base[key] = value
    return base


def env_name_for_path(prefix: str, path: Iterable[str]) -> str:
    return f"{prefix}_{'__'.join(part.upper() for part in path)}"


def format_dynaconf_value(value: Any) -> str:
    if isinstance(value, (list, dict)):
        return "@json " + json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def iter_dynaconf_env(
    config: Mapping[str, Any], prefix: str = DEFAULT_PREFIX
) -> Iterable[tuple[str, str]]:
    def walk(node: Any, path: tuple[str, ...]) -> Iterable[tuple[str, str]]:
        if isinstance(node, Mapping):
            for child_key, child_value in node.items():
                yield from walk(child_value, (*path, str(child_key)))
        else:
            yield env_name_for_path(prefix, path), format_dynaconf_value(node)

    for key, value in config.items():
        yield from walk(value, (str(key),))


def render_env_file(
    entries: Iterable[tuple[str, str]],
    *,
    source_files: list[Path],
    output_format: str,
    include_header: bool,
) -> str:
    lines: list[str] = []
    if include_header:
        lines.append("# Generated by toml_to_dynaconf_env.py")
        lines.append("# Do not commit generated files containing secrets.")
        if source_files:
            lines.append("# Source files:")
            lines.extend(f"# - {source_file}" for source_file in source_files)
        lines.append("")

    for key, value in entries:
        if output_format == "shell":
            lines.append(f"export {key}={shlex.quote(value)}")
        else:
            lines.append(f"{key}={value}")

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert one or more TOML files into environment variables using "
            "Dynaconf's DYNACONF_SECTION__KEY naming convention."
        )
    )
    parser.add_argument(
        "input_files",
        nargs="*",
        type=Path,
        help="TOML files to convert. Later files override earlier files.",
    )
    parser.add_argument(
        "--input",
        "-i",
        action="append",
        dest="input_options",
        type=Path,
        default=[],
        help="TOML file to convert. Can be provided multiple times.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Destination env file. Defaults to stdout.",
    )
    parser.add_argument(
        "--prefix",
        default=DEFAULT_PREFIX,
        help=f"Dynaconf environment variable prefix. Defaults to {DEFAULT_PREFIX}.",
    )
    parser.add_argument(
        "--format",
        choices=("env-file", "shell"),
        default="env-file",
        help="Output format. Use env-file for Docker Compose/systemd env files.",
    )
    parser.add_argument(
        "--ignore-missing",
        action="store_true",
        help="Skip missing input files instead of failing.",
    )
    parser.add_argument(
        "--no-header",
        action="store_true",
        help="Do not write generated-file comments.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_files: list[Path] = [*args.input_files, *args.input_options]
    if not input_files:
        print("No TOML input files provided.", file=sys.stderr)
        return 2

    config: dict[str, Any] = {}
    loaded_files: list[Path] = []
    for input_file in input_files:
        if not input_file.exists():
            if args.ignore_missing:
                continue
            print(f"Input file not found: {input_file}", file=sys.stderr)
            return 1

        merge_dicts(config, load_toml_file(input_file))
        loaded_files.append(input_file)

    content = render_env_file(
        iter_dynaconf_env(config, args.prefix),
        source_files=loaded_files,
        output_format=args.format,
        include_header=not args.no_header,
    )

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding="utf-8")
        os.chmod(args.output, 0o600)
    else:
        print(content, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
