[commons]
asterisk_pass = "super_secure_password"
asterisk_ami_secret = "secret"

[caller_sms]
twilio_account_sid = "super_secure_password"
twilio_auth_token = "super_secure_password"

[database]
db_password = 'super_secure_password'

[py_phone_caller_ui]
ui_secret_key = "super_secure_password"
