[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "caller-sms"
version = "1.0.0"
description = "Caller SMS service for py-phone-caller"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "py_phone_caller_utils",
    "aiohttp>=3.9.0",
    "twilio>=9.0.0",
]

[tool.setuptools.package-dir]
caller_sms = "."

[tool.setuptools.package-data]
caller_sms = ["*"]
