"""
Language names, flags, aliases, and Kokoro voice mappings.
"""

from typing import Dict

LANGUAGE_NAMES: Dict[str, str] = {
    "en": "English",
    "eng": "English",
    "en_US": "English (United States)",
    "en_GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "en-GB": "English (United Kingdom)",
    "es": "Spanish",
    "spa": "Spanish",
    "es_ES": "Spanish (Spain)",
    "es_MX": "Spanish (Mexico)",
    "es-ES": "Spanish (Spain)",
    "it": "Italian",
    "ita": "Italian",
    "it_IT": "Italian (Italy)",
    "it-IT": "Italian (Italy)",
    "fr": "French",
    "fra": "French",
    "fr_FR": "French (France)",
    "fr-FR": "French (France)",
    "de": "German",
    "deu": "German",
    "de_DE": "German (Germany)",
    "de-DE": "German (Germany)",
    "ru": "Russian",
    "rus": "Russian",
    "ru_RU": "Russian (Russia)",
    "ru-RU": "Russian (Russia)",
    "zh": "Chinese (Mandarin)",
    "cmn": "Chinese (Mandarin)",
    "zh_CN": "Chinese (Simplified)",
    "cmn-CN": "Chinese (Mandarin)",
    "hi": "Hindi",
    "hin": "Hindi",
    "hi_IN": "Hindi (India)",
    "hi-IN": "Hindi (India)",
    "indic": "Indic / Hindi",
    "he": "Hebrew",
    "heb": "Hebrew",
    "he_IL": "Hebrew (Israel)",
    "he-IL": "Hebrew (Israel)",
    "ar": "Arabic",
    "ara": "Arabic",
    "arb": "Arabic (Standard)",
    "ar_JO": "Arabic (Jordan)",
    "pt": "Portuguese",
    "por": "Portuguese",
    "pt_BR": "Portuguese (Brazil)",
    "ja": "Japanese",
    "jpn": "Japanese",
    "a": "English (American)",
    "b": "English (British)",
    "e": "Spanish",
    "f": "French",
    "h": "Hindi",
    "i": "Italian",
    "j": "Japanese",
    "p": "Portuguese (Brazil)",
    "z": "Chinese (Mandarin)",
}

LANGUAGE_FLAGS: Dict[str, str] = {
    "en": "🇬🇧",
    "eng": "🇬🇧",
    "en_US": "🇺🇸",
    "en-US": "🇺🇸",
    "en_GB": "🇬🇧",
    "en-GB": "🇬🇧",
    "a": "🇺🇸",
    "b": "🇬🇧",
    "es": "🇪🇸",
    "spa": "🇪🇸",
    "e": "🇪🇸",
    "es_ES": "🇪🇸",
    "es-ES": "🇪🇸",
    "es_MX": "🇲🇽",
    "it": "🇮🇹",
    "ita": "🇮🇹",
    "i": "🇮🇹",
    "it_IT": "🇮🇹",
    "it-IT": "🇮🇹",
    "fr": "🇫🇷",
    "fra": "🇫🇷",
    "f": "🇫🇷",
    "fr_FR": "🇫🇷",
    "fr-FR": "🇫🇷",
    "de": "🇩🇪",
    "deu": "🇩🇪",
    "de_DE": "🇩🇪",
    "de-DE": "🇩🇪",
    "ru": "🇷🇺",
    "rus": "🇷🇺",
    "ru_RU": "🇷🇺",
    "ru-RU": "🇷🇺",
    "zh": "🇨🇳",
    "cmn": "🇨🇳",
    "z": "🇨🇳",
    "zh_CN": "🇨🇳",
    "cmn-CN": "🇨🇳",
    "hi": "🇮🇳",
    "hin": "🇮🇳",
    "h": "🇮🇳",
    "hi_IN": "🇮🇳",
    "hi-IN": "🇮🇳",
    "indic": "🇮🇳",
    "he": "🇮🇱",
    "heb": "🇮🇱",
    "he_IL": "🇮🇱",
    "he-IL": "🇮🇱",
    "ar": "🇸🇦",
    "ara": "🇸🇦",
    "arb": "🇸🇦",
    "ar_JO": "🇯🇴",
    "pt": "🇵🇹",
    "por": "🇵🇹",
    "p": "🇧🇷",
    "pt_BR": "🇧🇷",
    "ja": "🇯🇵",
    "jpn": "🇯🇵",
    "j": "🇯🇵",
}

LANGUAGE_ALIASES: Dict[str, str] = {
    "a": "en",
    "b": "en",
    "eng": "en",
    "en_us": "en",
    "en-us": "en",
    "en_gb": "en",
    "en-gb": "en",
    "e": "es",
    "spa": "es",
    "es_es": "es",
    "es-es": "es",
    "es_mx": "es",
    "i": "it",
    "ita": "it",
    "it_it": "it",
    "it-it": "it",
    "f": "fr",
    "fra": "fr",
    "fr_fr": "fr",
    "fr-fr": "fr",
    "deu": "de",
    "de_de": "de",
    "de-de": "de",
    "rus": "ru",
    "ru_ru": "ru",
    "ru-ru": "ru",
    "z": "zh",
    "cmn": "zh",
    "zh_cn": "zh",
    "cmn-cn": "zh",
    "h": "hi",
    "hin": "hi",
    "hi_in": "hi",
    "hi-in": "hi",
}

KOKORO_VOICE_PREFIX_TO_LANG: Dict[str, str] = {
    "ff": "fr",
    "ef": "es",
    "em": "es",
    "if": "it",
    "im": "it",
    "zf": "zh",
    "zm": "zh",
    "jf": "ja",
    "jm": "ja",
    "hf": "hi",
    "hm": "hi",
    "pf": "pt",
    "pm": "pt",
    "bf": "en",
    "bm": "en",
    "af": "en",
    "am": "en",
}


def _kokoro_voice_to_lang(voice_name: str) -> str:
    return KOKORO_VOICE_PREFIX_TO_LANG.get(voice_name[:2], "en")
