apiVersion: v1
kind: Service
metadata:
  namespace: py-phone-caller
  name: caller-prometheus-webhook-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      name: http-8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: caller-prometheus-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: py-phone-caller
  name: caller-prometheus-webhook-deployment
  labels:
    app: caller-prometheus-webhook
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: caller-prometheus-webhook
  template:
    metadata:
      labels:
        app: caller-prometheus-webhook
    spec:
      containers:
        - name: caller-prometheus-webhook
          image: quay.io/py-phone-caller/caller_prometheus_webhook:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: DYNACONF_ASTERISK_CALL__ASTERISK_CALL_HOST
              value: "asterisk-caller-service"
            - name: DYNACONF_CALLER_SMS__CALLER_SMS_HOST
              value: "caller-sms-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: caller-config
              mountPath: /app/src/config/settings.toml
              subPath: settings.toml
      volumes:
        - name: caller-config
          configMap:
            name: py-phone-caller-config
